# PODNAME: MooX::Options::Docs::ImportedMethods
# ABSTRACT: The imported methods

=head1 DESCRIPTION

The list of the methods automatically imported into your class.

=head1 IMPORTED METHODS

=head2 options_usage

It display the usage message and return the exit code

  my $t = t->new_with_options();
  my $exit_code = 1;
  my $pre_message = "str is not valid";
  $t->options_usage($exit_code, $pre_message);

This method is also automatically fire if the command option "--help" is passed.

=head2 new_with_options

It will parse your command line params and your inline params, validate and call the 'new' method.

  myTools --str=ko

  t->new_with_options()->str # ko
  t->new_with_options(str => 'ok')->str #ok

=head2 option

The option keyword replace the 'has' method, and add support special option for the command line only.

See L<MooX::Options::Docs::Option> for the documentation.

=head1 SEE ALSO

L<MooX::Options>

L<Import parameters|MooX::Options::Docs::ImportParameters>
